import ConnectionSVG from 'assets/navigation/connection.svg'
import LibrarySVG from 'assets/navigation/library.svg'
import NowPlayingSVG from 'assets/navigation/nowPlaying.svg'
import PlaybackQueueSVG from 'assets/navigation/playbackQueue.svg'
import MenuSVG from 'assets/menu.svg'
import AlbumSVG from 'assets/library/album.svg'
import EmptyStar from 'assets/stars/empty_star.svg'
import HalfStar from 'assets/stars/half_star.svg'
import FullStar from 'assets/stars/full_star.svg'
import Pause from 'assets/controls/pause.svg'
import Play from 'assets/controls/play.svg'
import Next from 'assets/controls/next.svg'
import GitHubMark from 'assets/icons/github-mark.svg'
import GitHubMarkWhite from 'assets/icons/github-mark-white.svg'

export { ConnectionSVG, LibrarySVG, NowPlayingSVG, PlaybackQueueSVG, MenuSVG, AlbumSVG, EmptyStar, HalfStar, FullStar, Pause, Play, Next, GitHubMark, GitHubMarkWhite}
